## Importing Libraries

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Loading the dataset

In [45]:
data = pd.read_csv('E:\datasets\classification\seed_data.csv')

In [3]:
data.head()

area  perimeter  compactness  length  width  asymmetry  \
0  15.26      14.84       0.8710   5.763  3.312      2.221   
1  14.88      14.57       0.8811   5.554  3.333      1.018   
2  14.29      14.09       0.9050   5.291  3.337      2.699   
3  13.84      13.94       0.8955   5.324  3.379      2.259   
4  16.14      14.99       0.9034   5.658  3.562      1.355   

   length_kernel_groove  kernel  
0                 5.220       0  
1                 4.956       0  
2                 4.825       0  
3                 4.805       0  
4                 5.175       0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   area                  210 non-null    float64
 1   perimeter             210 non-null    float64
 2   compactness           210 non-null    float64
 3   length                210 non-null    float64
 4   width                 210 non-null    float64
 5   asymmetry             210 non-null    float64
 6   length_kernel_groove  210 non-null    float64
 7   kernel                210 non-null    int64  
dtypes: float64(7), int64(1)
memory usage: 13.2 KB


In [9]:
data.isnull().value_counts()

area   perimeter  compactness  length  width  asymmetry  length_kernel_groove  kernel
False  False      False        False   False  False      False                 False     210
dtype: int64

## Spiliting the dataset

In [17]:
x = data.drop('kernel',axis=1)

In [22]:
y=data['kernel']

In [23]:
x.head()

area  perimeter  compactness  length  width  asymmetry  \
0  15.26      14.84       0.8710   5.763  3.312      2.221   
1  14.88      14.57       0.8811   5.554  3.333      1.018   
2  14.29      14.09       0.9050   5.291  3.337      2.699   
3  13.84      13.94       0.8955   5.324  3.379      2.259   
4  16.14      14.99       0.9034   5.658  3.562      1.355   

   length_kernel_groove  
0                 5.220  
1                 4.956  
2                 4.825  
3                 4.805  
4                 5.175

In [24]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: kernel, dtype: int64

In [26]:
y.unique()

array([0, 1, 2], dtype=int64)

In [30]:
y.value_counts()

0    70
1    70
2    70
Name: kernel, dtype: int64

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.25,random_state=0)

In [36]:
xtrain.shape

(157, 7)

In [37]:
ytrain.shape

(157,)

In [38]:
xtest.shape

(53, 7)

In [39]:
ytest.shape

(53,)

## Feature scaling

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
scaler = StandardScaler()

In [40]:
xtrain = scaler.fit_transform(xtrain)

In [46]:
xtest = scaler.transform(xtest)

In [41]:
xtrain

array([[-0.74611567, -0.65972366, -1.02218665, ..., -0.90632233,
        -0.25413579, -0.34853337],
       [ 0.6223282 ,  0.69525799,  0.18452295, ...,  0.57172364,
        -1.09659973,  0.96335943],
       [-0.43215847, -0.52346852,  0.74704923, ..., -0.25267384,
        -0.73259674, -0.45616544],
       ...,
       [ 1.48229791,  1.44466125,  0.83324277, ...,  1.50550719,
        -0.40186643,  1.58884393],
       [ 0.06266537,  0.0139823 ,  0.80148726, ...,  0.33694377,
        -0.48571355, -0.46225783],
       [-1.20681373, -1.18960475, -1.30344978, ..., -1.30117937,
         0.41331392, -0.81764674]])

In [47]:
xtest

array([[-3.12718234e-01, -3.94783111e-01,  7.87877749e-01,
        -4.12031102e-01, -1.37951863e-01,  1.98372491e-01,
        -1.34971472e+00],
       [ 5.88202414e-01,  6.04421235e-01,  5.29297122e-01,
         5.57990669e-01,  5.77059541e-01,  1.22716337e+00,
         9.69451815e-01],
       [-2.95655343e-01, -2.81237162e-01,  9.83294085e-02,
        -8.72072982e-02, -2.68681560e-01, -1.04070165e+00,
        -7.93277218e-01],
       [-1.45501902e-01, -2.50958243e-01,  1.10996941e+00,
        -5.29946593e-01,  1.63526826e-01, -8.15778413e-01,
        -9.07001672e-01],
       [-1.22046404e+00, -1.30315070e+00, -5.09561892e-01,
        -1.19071830e+00, -1.14643810e+00,  2.55274644e+00,
        -9.04970878e-01],
       [ 1.62562619e+00,  1.66418342e+00,  3.29691023e-01,
         1.69042434e+00,  1.39078521e+00, -1.47457723e+00,
         1.76755379e+00],
       [ 1.41745892e+00,  1.25541801e+00,  1.68156869e+00,
         9.49559090e-01,  1.72427933e+00,  4.29950257e-01,
         7.0544861

# Logistic Regression

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
Lr = LogisticRegression()

In [50]:
Lr.fit(xtrain,ytrain)

LogisticRegression()

## Predicting the test_input

In [51]:
y_predict = Lr.predict(xtest)

In [52]:
y_predict

array([0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 0, 2, 0, 2, 1, 1, 2, 0, 0, 0, 2, 0,
       0, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 1, 2, 2, 2, 1, 0, 0, 2, 0, 1, 2,
       0, 1, 1, 0, 2, 1, 0, 1, 2], dtype=int64)

# Accuracy of the predicted value

In [53]:
#building confusion matrix
from sklearn.metrics import confusion_matrix

In [57]:
cm = confusion_matrix(ytest,y_predict)

In [58]:
cm

array([[16,  0,  1],
       [ 3, 18,  0],
       [ 0,  0, 15]], dtype=int64)

In [60]:
#finding accuracy score
from sklearn.metrics import accuracy_score
ac = accuracy_score(ytest,y_predict)

In [61]:
ac

0.9245283018867925